name: Shell Commands 

on: [push]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script 
        run: |
           node -v 
      - name: Using a python interpreter
        run: |
          import platform 
          print(platform.processor())
        shell: python
  run-windwos:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 
