# This is a basic workflow to help deploy my app to Azure
name: "CI/CD Pipeline for Azure webapp deployment"


# Controls when the action will run. 
on:

# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, closed]
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Building Job
    steps:
      - uses: actions/checkout@v2
        
          

  deploy:
    name: Deploying to Azure server
    runs-on: ubuntu-latest
    env:
      SECRET_NAME: ${{secrets.GITHUB_CREDENTIAL_NAME}}
      SECRET_PASSWORD: ${{secrets.GITHUB_CREDENTIAL_PASSWORD}}

    if: github.ref == 'refs/heads/master' && job.status == 'success'
    run: |
      git remote add [repo link]
      git push -u origin HEAD:master -f

    steps:
      -uses: actions/checkout@v2
      -name: credentials
      -uses: azure/static-web-apps-deploy@v0.0.1-preview
       with:
          key: ${{ secrets.AZURE_CREDENTIAL }}
          
