name: simple workflow
on: [push]
jobs:
    job1:
      name: first job
      runs-on: ubuntu-latest
      steps:
      - name: step one checkout
        uses: actions/checkout@v1
      - name: step two
        run: date  

    job2:
      name: second job      
      runs-on: windows-latest
      steps:
      - name: step one
        uses: actions/checkout@v1
      - name: step two
        run: date

    job3:
      name: third job      
      runs-on: macos-latest
      steps:
      - name: step one
        uses: actions/checkout@v1
      - name: step two
        run: date

    job4:
      name: fourth job

      needs: [job1, job2, job3]
      runs-on: macos-latest
      steps:
      - name: step one
        uses: action/checkout@v1
      - name: step two
        run: date

        
